### ISSUE TITLE
No save button on Linux 

### ISSUE THREAD

**Issue by rolodoom** [kienphanhuy/Cuki-IR-generator#1]
I'm testing this script on Linux Manjaro GNU Octave but there is no save button. ¿Is there a way to fix this?

GNU Octave version 6.4.0
Linux 5.10.79-1-MANJARO

![Screenshot_20211130_113457](https://user-images.githubusercontent.com/61945227/144088875-efa58ca7-4ab4-4641-96f8-40c5a554a1d0.png)

**Comment by kienphanhuy** [comment]
It is a problem indeed...

It is only made for pc or Mac

Do you have any computing knowledge?

There are some lines with a "if" test

That are "ispc" or "Ismac"

**Comment by lpinner** [comment]
I ran into this last week as well. 

By replacing all occurrences of `ispc` with `ispc|isunix` I got it to work. I never got playback to work, but that's another issue, but saving the IRs worked fine.

**Comment by lpinner** [comment]
![image](https://user-images.githubusercontent.com/4827816/144195201-3a950752-5394-40ac-abef-70931b08b82b.png)

**Comment by kienphanhuy** [comment]
It's weird you could not play... Did you use your audio interface
headphones output or expected the sound to come from your computer built-in
speaker?
Maybe jack is not configured properly...

Did the recording work?

If you are struggling too much with linux, just send me a dropbox/google
drive link to with 2 channels recordings (1 channel being mic and the other
the pickup) and I'll make the IR with my algorithm which is more accurate
than the "light" github version.

Cheers,
Cuki


Le mer. 1 déc. 2021 à 09:04, Luke Pinner ***@***.***> a
écrit :

**Comment by rolodoom** [comment]
Thanks @kienphanhuy and @lpinner for the answer. I changed `ispc` with `ispc|isunix` and everything work as expected.
