### ISSUE TITLE
Load wav option with PickUp / MIC recording [Feature Request]

### ISSUE THREAD

**Issue by rolodoom** [kienphanhuy/Cuki-IR-generator#2]
Hello there. This is more like a feature request rather than an issue, great script by the way.

It's there anyway to load the wav file with the PickUp / Mic signal already recorded?

It would be a nice feature to have the option to record or to load de recording.

**Comment by kienphanhuy** [comment]
Un comment lines 234 and to 234

**Comment by kienphanhuy** [comment]
File must be stereo 
Pickup track must be on the left
Mic track must be on the right

**Comment by kienphanhuy** [comment]
It was always there...

**Comment by rolodoom** [comment]
This is great!!! Thanks a lot!

**Comment by rolodoom** [comment]
I'm using Ocatve on Linux Manjaro, uncommented line 234 on `Cuki_IR_gen1r.m` but don't see any button when running the script.

Any idea?

**Comment by lpinner** [comment]
I think @kienphanhuy meant Uncomment lines 231 to 234

![image](https://user-images.githubusercontent.com/4827816/145936264-c6109ccf-a68e-4497-b1d0-19a02515c99e.png)

**Comment by kienphanhuy** [comment]
Thanks @lpinner 

I indeed mistype. Lie 231 adds the bouton.
That's the line to uncomment

**Comment by rolodoom** [comment]
Totally Works!!! Thanks!!!
