### ISSUE TITLE
GUI version doesn't generate the IR graph image properly

### ISSUE THREAD

**Issue by pokibg** [kienphanhuy/Cuki-IR-generator#4]
Hello Cuki.

Admiration for this tool/script, it is amazing.

The GUI(cuki_ir_gen1r.m) is buggy here, the graph image is not generated properly. 
Not a big deal for the final IR, but the test recording is miss leading - it looks like there is no signal.

Otherwise the script seems to operate just fine. 
The CLI version(IRgen2.m) generates the image normally.

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19044 N/A Build 19044
Octave version:          7.1.0 (x86_64)

Let me know if I can help you on this. 

Below you can see the image I get.

Best regards.

![IR_itp](https://user-images.githubusercontent.com/104040679/164618811-36e6e061-7aa8-4dbc-be80-648c610b224a.jpg)

**Comment by kienphanhuy** [comment]
I did not install the last Octave version... GUI are always a problem.

Did you try changing the size of the window?

In the begining of the code all the GUI is set. Feel free to make your own version

**Comment by kienphanhuy** [comment]
There is a non GUI version on the 2nd branch of this Github

[https://github.com/kienphanhuy/Cuki-IR-generator/blob/84d4aec200d5662cae1a9bbe22ac1eb7e15b28d4/IRgen2.m](url)

It should be used as
% To be used as
%  IRgen2('filename.wav')
% filename must be a stereo file with a recording of the acoustic guitar (around 1-3 min) 
% Left: Pickup track
% Right: Microphone track

**Comment by pokibg** [comment]
As I already mentioned, the non GUI(CLI) version is working just fine.

Yea, I have tried resizing the window. 
The problem is present not only on the preview, but on the generated output image when saving the IR.

I will try to mess around with the settings and report back if I manage to find a fix.

Regards.

**Comment by pokibg** [comment]
Quick update.

It seems that the plot function is removing the previously drawn plots instead of combining them in a single graph.

So for the image of the test recording, only the black bar at -0.1 is seen.
Commenting both:

  plot(ax,[t(1) t(Nb)],[0.1 0.1],'Color','k','linewidth',3)
  plot(ax,[t(1) t(Nb)],[-0.1 -0.1],'Color','k','linewidth',3)

Or simply moving the signal plot after them is looking like a normal graph of the signal.

I guess they changed the plot function somehow. Looking further onto this.

update: seems like the "hold on" is not working as it should.
Don't bother with it - almost got it fixed. I will keep you updated.

**Comment by pokibg** [comment]
Hey Cuki, not sure if this is the proper way to do it, but I have never used github nor I am a programmer.

I think I managed to fix the issue. I also did some other changes, I hope that you will like and accept them - if not, please accept my apologies and discard whatever you think is not needed.

In summary.

1) The hold on/hold off were not working as intended.

I included initial parameters when defining the axes, which tells them to merge the new plots, instead of replacing the previous ones..
```
ax = axes('NextPlot', 'add');
ax2 = axes('NextPlot', 'add');
```
I removed all the "hold on" and "hold off" clauses.

2) At some points in the scripts there was no definition which axes is used, which caused strange behavior - some things were drawn on the wrong graph. **At this point I realized that this was the reason for the "hold on" problem as well.. but I have already fixed it the other way**

So I have selected the appropriate axes here and there, mostly:

`axes(ax)`

3) I have altered the IR frequency graph image a little bit. I have included horizontal line at Y=0 (0dB).
I have defined ticks and labels on the X-axis to reflect the frequency band better.

4) I fixed the image generation of the recordings, in case you are redoing them after you have computed the IR.
Setting the axes back to linear, resetting the ticks and so on. I also tweaked the xlim and ylim definitions, because they were kinda off sometimes.

5) Changed the grid of the ax axes from "on" to "minor" - looks more sexy.
grid (ax, 'minor');

I think this is pretty much everything, you can always diff the file with the one you have.

I am attaching the altered script, I have changed the last letter from "r" to "s" in order to differentiate them.

Best regards.

[cuki_ir_gen1s.m.txt](https://github.com/kienphanhuy/Cuki-IR-generator/files/8544806/cuki_ir_gen1s.m.txt)

**Comment by kienphanhuy** [comment]
Thank you pokibg!

I just installed Octave 7.1 and indeed the GUI is buggy. I uploaded your version as the last update and aknowledge your  contribution.

Cheers,
Cuki

**Comment by pokibg** [comment]
Nothing to thank me for! 
It is all you for making this open source and giving it to the community! :)

I am glad that I could contribute with something to the project - thanks for letting me so.

I actually have a lot ideas - UI-wise, unfortunately I am very bad at math and cannot even understand the equations in your algorithm. I wish I could help there as well.

If you are open to future contributions from me, just let me know. 

I would be more than happy to provide as much as I can to this beautiful project.

All best wishes, Cuki!
Best regards.

p.s you may close the issue if you like
